POST http://127.0.0.1:8000/login
Content-Type: application/json

{ "username": "admin002", "password": "Pass1234"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{ "username": "admin002", "password": "Pass1234", "email": "admin@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token e61756255626a57e22fd3195f5a076b55b6fcb56

{}

###

POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Tokene 61756255626a57e22fd3195f5a076b55b6fcb56

{}

###

DELETE http://127.0.0.1:8000/users/10/delete/
Authorization: Token e61756255626a57e22fd3195f5a076b55b6fcb56

{}

